### ISSUE TITLE
copy-on-write and spaces in names

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/hatrac#63] opened 2023-08-26 06:26 UTC
dev.atlas-d2k is set up like this:

```
"overlay_backends": [
	{
	    "storage_backend": "filesystem",
	    "storage_path": "/var/www/hatrac"
	},
	{
	    "storage_backend": "amazons3",
	    "s3_config": {
		"session": {
		    "region_name": "us-west-2"
		},
		"buckets": {
		    "/": {
			"bucket_name": "prod.rebuildingakidney.org",
			"region_name": "us-west-2",
			"presigned_url_expiration_secs": 600,
			"presigned_url_size_threshold": 10480000
		    },
		    "/resources2": {
			"bucket_name": "encrypted.prod.rebuildingakidney.org",
			"region_name": "us-west-2",
			"presigned_url_expiration_secs": 600,
			"presigned_url_size_threshold": 10480000
		    }
		}
	    }
	}
    ]
```

So far everything seems to be working fine, except for files in namespaces with spaces in the namespace names. For example:
```
dev::laura[~] curl https://www.atlas-d2k.org/hatrac/resources/test/without_spaces/small.txt
hello
dev::laura[~] curl https://www.atlas-d2k.org/hatrac/resources/test/with%20spaces/small.txt
hello
dev::laura[~] curl https://dev.atlas-d2k.org/hatrac/resources/test/without_spaces/small.txt
hello
dev::laura[~] curl https://dev.atlas-d2k.org/hatrac/resources/test/with%20spaces/small.txt
Resource /hatrac/resources/test/with%20spaces/small.txt not found.
dev::laura[~] curl "https://dev.atlas-d2k.org/hatrac/resources/test/with spaces/small.txt"
Resource /hatrac/resources/test/with not found.
dev::laura[~] curl "https://dev.atlas-d2k.org/hatrac/resources/test/with\ spaces/small.txt"
Resource /hatrac/resources/test/with\ not found.
dev::laura[~] deriva-hatrac-cli --host www.atlas-d2k.org ls /hatrac/resources/test
/hatrac/resources/test/without_spaces
/hatrac/resources/test/with%20spaces
dev::laura[~] deriva-hatrac-cli --host dev.atlas-d2k.org ls /hatrac/resources/test
/hatrac/resources/test/without_spaces
/hatrac/resources/test/with%20spaces
dev::laura[~] deriva-hatrac-cli --host www.atlas-d2k.org ls "/hatrac/resources/test/with%20spaces"
/hatrac/resources/test/with%20spaces/small.txt
dev::laura[~] deriva-hatrac-cli --host dev.atlas-d2k.org ls "/hatrac/resources/test/with%20spaces"
Unexpected error occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deriva/core/hatrac_cli.py", line 296, in main
    args.func(args)
  File "/usr/local/lib/python3.9/site-packages/deriva/core/hatrac_cli.py", line 143, in list
    for name in namespaces:
TypeError: 'NoneType' object is not iterable
```

Here's what's in the database for that file (this is from dev.atlas-d2k.org)
```
dev::laura[~] sudo -u hatrac psql -c "select * from name where name = '/resources/test/with spaces/small.txt'"
   id   |  pid   |      ancestors      |                 name                  | subtype | is_deleted |                             owner                              | create | update | re
ad | subtree-owner | subtree-create | subtree-update | subtree-read 
--------+--------+---------------------+---------------------------------------+---------+------------+----------------------------------------------------------------+--------+--------+---
---+---------------+----------------+----------------+--------------
 373205 | 373203 | {1,2,373197,373203} | /resources/test/with spaces/small.txt |       1 | f          | {https://auth.globus.org/a4e03698-d274-11e5-9a48-8b6f49eb5587} |        |        |   
   |               |                |                | 
(1 row)

dev::laura[~] sudo -u hatrac psql -c "select * from version where nameid = 373205"
   id   | nameid |             version              | nbytes | is_deleted |                             owner                              | read |                                     metad
ata                                      | aux 
--------+--------+----------------------------------+--------+------------+----------------------------------------------------------------+------+------------------------------------------
-----------------------------------------+-----
 367737 | 373205 | UB8MDJlkW6Ha4xPUrDBhyqZHaeM64zq0 |      6 | f          | {https://auth.globus.org/a4e03698-d274-11e5-9a48-8b6f49eb5587} |      | {"content-md5": "b1946ac92492d2347c6235b4
d2611184", "content-type": "text/plain"} | 
(1 row)
```

Here are log entries from `curl https://dev.atlas-d2k.org/hatrac/resources/test/with%20spaces/small.txt` and `curl "https://dev.atlas-d2k.org/hatrac/resources/test/with spaces/small.txt"`
```
Aug 26 02:16:43 dev.atlas-d2k.org hatrac[24293.140003969492544]: {"elapsed":0.004528, "req":"aai0xhv4kYs=", "trace":"404 Not Found: Resource /hatrac/resources/test/with%20spaces/small.txt not found.", "client":"128.182.76.53"}
Aug 26 02:16:43 dev.atlas-d2k.org hatrac[24293.140003969492544]: {"elapsed":0.005339000000000001, "req":"aai0xhv4kYs=", "scheme":"https", "host":"dev.atlas-d2k.org", "status":"404 NOT FOUND", "method":"GET", "path":"/hatrac/resources/test/with%20spaces/small.txt", "range":"*/67", "type":"text/plain", "client":"128.182.76.53", "agent":"curl/7.76.1"}
Aug 26 02:19:27 dev.atlas-d2k.org hatrac[24292.140003944314432]: {"elapsed":0.004684000000000001, "req":"M/9I8wjkgu4=", "trace":"404 Not Found: Resource /hatrac/resources/test/with not found.", "client":"128.182.76.53"}
Aug 26 02:19:27 dev.atlas-d2k.org hatrac[24292.140003944314432]: {"elapsed":0.005076, "req":"M/9I8wjkgu4=", "scheme":"https", "host":"dev.atlas-d2k.org", "status":"404 NOT FOUND", "method":"GET", "path":"/hatrac/resources/test/with", "range":"*/48", "type":"text/plain", "client":"128.182.76.53", "agent":"curl/7.76.1"}
```

dev.atlas-d2k.org is running the latest master version.

**Comment by karlcz** [comment] 2023-08-29 18:07
Yuck, I think this is from bugs in the old web.py codebase... it wasn't supposed to be unquoting the names when storing them in the DB nor in the backend.

Could you check how resources/test/with%20spaces/small.txt is named in your actual S3 prod bucket?  I.e. with the CLI `asw s3 ls s3://prod.rebuildingakidney.org/...`?

I am hoping it will show you something like:

```
          PRE with%spaces/
```

so the unquoting is only in the hatrac DB and not in the backend as well. Similarly, I'd expect to actually see a directory called `with%20spaces` in the filesystem if you were using a filesystem backend.

The newer flask codebase behaves this way and also stores the original quoted name in the DB. So, there is an incompatibility when trying to use the code with a legacy database created from the older web.py codebase...

**Comment by ljpearlman** [comment] 2023-08-29 19:07
Bad news:
```
www::hatrac[~] aws s3 ls "s3://prod.rebuildingakidney.org/hatrac/resources/test/with spaces"
 
                           PRE with spaces/
www::hatrac[~] 
www::hatrac[~] aws s3 ls "s3://prod.rebuildingakidney.org/hatrac/resources/test/with%20spaces"
www::hatrac[~] 
```

**Comment by karlcz** [comment] 2023-08-29 19:33
Yup.  Using the old webpy codebase, I also reproduced this and the same behavior on the filesystem backend.

**Comment by karlcz** [comment] 2023-09-06 17:55
Partial fixes to address this were merged for the `amazons3` backend by enabling a new bucket configuration option `unquote_object_keys` to `true`.  This can allow a bucket to be operated in the legacy-compatible quoting mode.

However, there are caveats for now:
1. We decided _not_ to support this for the filesystem, because unlike S3 buckets, a filesystem can support cheap renames to cleanup the legacy unquoted names.
2. You also still need to fixup the legacy hatrac DB `name` table before you can successfully resume operations on your legacy bucket.

## Fixing up names

We decided that admins should manually intervene to control this update step (or think about alternative plans, as needed). You could detect your problematic `name` table records with this query:

```
SELECT name FROM name WHERE name ~ '[^-_.~A-Za-z0-9/]';
```

i.e. where the name is not a valid hatrac URL path, because unquoting was already performed. To fix this, you need to reapply quoting in the DB names, and also capture the list of transformed names if you need to perform the same renames in a filesystem backend.

**Closed** 2023-11-02 17:20 UTC
